spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USUARIO}
spring.datasource.password=${SUPABASE_DB_SENHA}

supabase.url=${SUPABASE_URL}
supabase.secret-key=${SUPABASE_SECRET_KEY}
supabase.bucket=${SUPABASE_BUCKET}

spring.servlet.multipart.max-file-size=7MB
spring.servlet.multipart.max-request-size=6MB


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=public

server.port=8080